version: "3.9"

services:
  db:
    image: postgres:15
    container_name: entropy-postgres
    restart: always
    environment:
      POSTGRES_USER: entropy_user
      POSTGRES_PASSWORD: entropy_pass
      POSTGRES_DB: entropy_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
